auth0:
  audience: https://currency-converter-service.herokuapp.com/
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:currency_converter_db
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-3u2hq9mr.us.auth0.com/